"builtin.module"() ({
  "elenor.runtime.tile_group_task"() <{task_name = "tiled_matmul_pipelined_task", completion_event = "group_task_done"}> ({
  ^bb0:
  }, {
    "elenor.runtime.tile_role"() <{role_id = 0 : index, tile_mask = 15 : index}> ({
      "elenor.runtime.tile_program"() <{program_name = "tiled_matmul_4k_tile", version = 1 : index}> ({
        "elenor.mfe.descriptor"() <{descriptor_name = "load_A_k0", op_name = "load", params = {bytes = 16384 : index, ops = 0 : index}}> : () -> ()
        "elenor.mfe.descriptor"() <{descriptor_name = "load_B_k0", op_name = "load", params = {bytes = 16384 : index, ops = 0 : index}}> : () -> ()
        "elenor.mfe.descriptor"() <{descriptor_name = "load_A_k1", op_name = "load", params = {bytes = 16384 : index, ops = 0 : index}}> : () -> ()
        "elenor.mfe.descriptor"() <{descriptor_name = "load_B_k1", op_name = "load", params = {bytes = 16384 : index, ops = 0 : index}}> : () -> ()
        "elenor.boa.descriptor"() <{descriptor_name = "matmul_k0", op_name = "matmul", params = {accumulate = false, chunk = 0 : index, k = 64 : index, m = 128 : index, n = 128 : index, ops = 2097152 : index}}> : () -> ()
        "elenor.mfe.descriptor"() <{descriptor_name = "store_C_k0", op_name = "store", params = {bytes = 32768 : index, chunk = 0 : index, ops = 0 : index}}> : () -> ()
        "elenor.mfe.descriptor"() <{descriptor_name = "load_A_k2", op_name = "load", params = {bytes = 16384 : index, ops = 0 : index}}> : () -> ()
        "elenor.mfe.descriptor"() <{descriptor_name = "load_B_k2", op_name = "load", params = {bytes = 16384 : index, ops = 0 : index}}> : () -> ()
        "elenor.boa.descriptor"() <{descriptor_name = "matmul_k1", op_name = "matmul", params = {accumulate = true, chunk = 1 : index, k = 64 : index, m = 128 : index, n = 128 : index, ops = 2097152 : index}}> : () -> ()
        "elenor.mfe.descriptor"() <{descriptor_name = "store_C_k1", op_name = "store", params = {bytes = 32768 : index, chunk = 1 : index, ops = 0 : index}}> : () -> ()
        "elenor.mfe.descriptor"() <{descriptor_name = "load_A_k3", op_name = "load", params = {bytes = 16384 : index, ops = 0 : index}}> : () -> ()
        "elenor.mfe.descriptor"() <{descriptor_name = "load_B_k3", op_name = "load", params = {bytes = 16384 : index, ops = 0 : index}}> : () -> ()
        "elenor.boa.descriptor"() <{descriptor_name = "matmul_k2", op_name = "matmul", params = {accumulate = true, chunk = 2 : index, k = 64 : index, m = 128 : index, n = 128 : index, ops = 2097152 : index}}> : () -> ()
        "elenor.mfe.descriptor"() <{descriptor_name = "store_C_k2", op_name = "store", params = {bytes = 32768 : index, chunk = 2 : index, ops = 0 : index}}> : () -> ()
        "elenor.boa.descriptor"() <{descriptor_name = "matmul_k3", op_name = "matmul", params = {accumulate = true, chunk = 3 : index, k = 64 : index, m = 128 : index, n = 128 : index, ops = 2097152 : index}}> : () -> ()
        "elenor.mfe.descriptor"() <{descriptor_name = "store_C_k3", op_name = "store", params = {bytes = 32768 : index, chunk = 3 : index, ops = 0 : index}}> : () -> ()
      }, {
        "elenor.runtime.tile.launch.mfe"() <{descriptor = "load_A_k0", event = "e_a0", comment = "prefetch A chunk 0"}> : () -> ()
        "elenor.runtime.tile.launch.mfe"() <{descriptor = "load_B_k0", event = "e_b0", comment = "prefetch B chunk 0"}> : () -> ()
        "elenor.runtime.tile.launch.mfe"() <{descriptor = "load_A_k1", event = "e_a1", comment = "prefetch A chunk 1 (overlap)"}> : () -> ()
        "elenor.runtime.tile.launch.mfe"() <{descriptor = "load_B_k1", event = "e_b1", comment = "prefetch B chunk 1 (overlap)"}> : () -> ()
        "elenor.runtime.tile.waitall"() <{events = ["e_a0", "e_b0"], comment = "operands for chunk 0 ready"}> : () -> ()
        "elenor.runtime.tile.launch.boa"() <{descriptor = "matmul_k0", event = "e_mm0", comment = "BOA accumulate chunk 0"}> : () -> ()
        "elenor.runtime.tile.wait"() <{event = "e_mm0", comment = "BOA chunk 0 done"}> : () -> ()
        "elenor.runtime.tile.launch.mfe"() <{descriptor = "store_C_k0", event = "e_store0", comment = "MFE store result chunk 0 (deferred wait)"}> : () -> ()
        "elenor.runtime.tile.launch.mfe"() <{descriptor = "load_A_k2", event = "e_a2", comment = "prefetch A chunk 2 (overlap)"}> : () -> ()
        "elenor.runtime.tile.launch.mfe"() <{descriptor = "load_B_k2", event = "e_b2", comment = "prefetch B chunk 2 (overlap)"}> : () -> ()
        "elenor.runtime.tile.waitall"() <{events = ["e_a1", "e_b1"], comment = "operands for chunk 1 ready"}> : () -> ()
        "elenor.runtime.tile.launch.boa"() <{descriptor = "matmul_k1", event = "e_mm1", comment = "BOA accumulate chunk 1"}> : () -> ()
        "elenor.runtime.tile.wait"() <{event = "e_store0", comment = "drain store 0 (overlap BOA1)"}> : () -> ()
        "elenor.runtime.tile.wait"() <{event = "e_mm1", comment = "BOA chunk 1 done"}> : () -> ()
        "elenor.runtime.tile.launch.mfe"() <{descriptor = "store_C_k1", event = "e_store1", comment = "MFE store result chunk 1 (deferred wait)"}> : () -> ()
        "elenor.runtime.tile.launch.mfe"() <{descriptor = "load_A_k3", event = "e_a3", comment = "prefetch A chunk 3 (overlap)"}> : () -> ()
        "elenor.runtime.tile.launch.mfe"() <{descriptor = "load_B_k3", event = "e_b3", comment = "prefetch B chunk 3 (overlap)"}> : () -> ()
        "elenor.runtime.tile.waitall"() <{events = ["e_a2", "e_b2"], comment = "operands for chunk 2 ready"}> : () -> ()
        "elenor.runtime.tile.launch.boa"() <{descriptor = "matmul_k2", event = "e_mm2", comment = "BOA accumulate chunk 2"}> : () -> ()
        "elenor.runtime.tile.wait"() <{event = "e_store1", comment = "drain store 1 (overlap BOA2)"}> : () -> ()
        "elenor.runtime.tile.wait"() <{event = "e_mm2", comment = "BOA chunk 2 done"}> : () -> ()
        "elenor.runtime.tile.launch.mfe"() <{descriptor = "store_C_k2", event = "e_store2", comment = "MFE store result chunk 2 (deferred wait)"}> : () -> ()
        "elenor.runtime.tile.waitall"() <{events = ["e_a3", "e_b3"], comment = "operands for chunk 3 ready"}> : () -> ()
        "elenor.runtime.tile.launch.boa"() <{descriptor = "matmul_k3", event = "e_mm3", comment = "BOA accumulate chunk 3"}> : () -> ()
        "elenor.runtime.tile.wait"() <{event = "e_store2", comment = "drain store 2 (overlap BOA3)"}> : () -> ()
        "elenor.runtime.tile.wait"() <{event = "e_mm3", comment = "BOA chunk 3 done"}> : () -> ()
        "elenor.runtime.tile.launch.mfe"() <{descriptor = "store_C_k3", event = "e_store3", comment = "MFE store result chunk 3 (deferred wait)"}> : () -> ()
        "elenor.runtime.tile.wait"() <{event = "e_store3", comment = "drain last store"}> : () -> ()
        "elenor.runtime.tile.ret"() : () -> ()
      }) : () -> ()
    }) : () -> ()
    "elenor.runtime.tile_role"() <{role_id = 1 : index, tile_mask = 15 : index}> ({
      "elenor.runtime.tile_program"() <{program_name = "pow_4k_tile", version = 1 : index}> ({
        "elenor.mfe.descriptor"() <{descriptor_name = "load_pow", op_name = "load", params = {bytes = 32768 : index, ops = 0 : index}}> : () -> ()
        "elenor.evu.descriptor"() <{descriptor_name = "pow_chunk", op_name = "pow", params = {bytes = 32768 : index, exponent = 2 : index, ops = 65536 : index}}> : () -> ()
        "elenor.mfe.descriptor"() <{descriptor_name = "store_pow", op_name = "store", params = {bytes = 32768 : index, ops = 0 : index}}> : () -> ()
      }, {
        "elenor.runtime.tile.launch.mfe"() <{descriptor = "load_pow", event = "e_load", comment = "load pow input L2->L1"}> : () -> ()
        "elenor.runtime.tile.wait"() <{event = "e_load", comment = "pow input ready"}> : () -> ()
        "elenor.runtime.tile.launch.evu"() <{descriptor = "pow_chunk", event = "e_pow", comment = "EVU pow on one tile chunk"}> : () -> ()
        "elenor.runtime.tile.wait"() <{event = "e_pow", comment = "pow chunk done"}> : () -> ()
        "elenor.runtime.tile.launch.mfe"() <{descriptor = "store_pow", event = "e_store", comment = "store pow output L1->L2"}> : () -> ()
        "elenor.runtime.tile.wait"() <{event = "e_store", comment = "drain pow output"}> : () -> ()
        "elenor.runtime.tile.ret"() : () -> ()
      }) : () -> ()
    }) : () -> ()
  }, {
    "elenor.runtime.group.dma_prefetch"() <{descriptor = "gdma_prefetch_pow0", l2_slot = "l2_buf_pow0", event = "ev_dma_pow_in0", bytes_total = 131072 : index, comment = "Pow input chunk 0 HBM->L2"}> : () -> ()
    "elenor.runtime.group.dma_prefetch"() <{descriptor = "gdma_prefetch_pow1", l2_slot = "l2_buf_pow1", event = "ev_dma_pow_in1", bytes_total = 131072 : index, comment = "Pow input chunk 1 HBM->L2"}> : () -> ()
    "elenor.runtime.group.dma_prefetch"() <{descriptor = "gdma_prefetch_pow2", l2_slot = "l2_buf_pow2", event = "ev_dma_pow_in2", bytes_total = 131072 : index, comment = "Pow input chunk 2 HBM->L2"}> : () -> ()
    "elenor.runtime.group.dma_prefetch"() <{descriptor = "gdma_prefetch_pow3", l2_slot = "l2_buf_pow3", event = "ev_dma_pow_in3", bytes_total = 131072 : index, comment = "Pow input chunk 3 HBM->L2"}> : () -> ()
    "elenor.runtime.group.wait_event"() <{event = "ev_dma_pow_in0", comment = "Pow chunk 0 input visible in L2"}> : () -> ()
    "elenor.runtime.group.dispatch_role"() <{role_id = 1 : index, event = "ev_role_pow0", comment = "Launch pow tile program for chunk 0"}> : () -> ()
    "elenor.runtime.group.wait_event"() <{event = "ev_dma_pow_in1", comment = "Pow chunk 1 input visible in L2"}> : () -> ()
    "elenor.runtime.group.dispatch_role"() <{role_id = 1 : index, event = "ev_role_pow1", comment = "Launch pow tile program for chunk 1"}> : () -> ()
    "elenor.runtime.group.wait_event"() <{event = "ev_dma_pow_in2", comment = "Pow chunk 2 input visible in L2"}> : () -> ()
    "elenor.runtime.group.dispatch_role"() <{role_id = 1 : index, event = "ev_role_pow2", comment = "Launch pow tile program for chunk 2"}> : () -> ()
    "elenor.runtime.group.wait_event"() <{event = "ev_dma_pow_in3", comment = "Pow chunk 3 input visible in L2"}> : () -> ()
    "elenor.runtime.group.dispatch_role"() <{role_id = 1 : index, event = "ev_role_pow3", comment = "Launch pow tile program for chunk 3"}> : () -> ()
    "elenor.runtime.group.dma_prefetch"() <{descriptor = "gdma_prefetch_A0", l2_slot = "l2_buf_A0", event = "ev_dma_A0", bytes_total = 262144 : index, comment = "Group DMA prefetch A chunk 0 HBM->L2"}> : () -> ()
    "elenor.runtime.group.dma_prefetch"() <{descriptor = "gdma_prefetch_B0", l2_slot = "l2_buf_B0", event = "ev_dma_B0", bytes_total = 65536 : index, comment = "Group DMA prefetch B chunk 0 HBM->L2"}> : () -> ()
    "elenor.runtime.group.dma_prefetch"() <{descriptor = "gdma_prefetch_A1", l2_slot = "l2_buf_A1", event = "ev_dma_A1", bytes_total = 262144 : index, comment = "Group DMA prefetch A chunk 1 (overlap compute g=0)"}> : () -> ()
    "elenor.runtime.group.dma_prefetch"() <{descriptor = "gdma_prefetch_B1", l2_slot = "l2_buf_B1", event = "ev_dma_B1", bytes_total = 65536 : index, comment = "Group DMA prefetch B chunk 1 (overlap compute g=0)"}> : () -> ()
    "elenor.runtime.group.dma_prefetch"() <{descriptor = "gdma_prefetch_A2", l2_slot = "l2_buf_A2", event = "ev_dma_A2", bytes_total = 262144 : index, comment = "Group DMA prefetch A chunk 2 (overlap compute g=1)"}> : () -> ()
    "elenor.runtime.group.dma_prefetch"() <{descriptor = "gdma_prefetch_B2", l2_slot = "l2_buf_B2", event = "ev_dma_B2", bytes_total = 65536 : index, comment = "Group DMA prefetch B chunk 2 (overlap compute g=1)"}> : () -> ()
    "elenor.runtime.group.dma_prefetch"() <{descriptor = "gdma_prefetch_A3", l2_slot = "l2_buf_A3", event = "ev_dma_A3", bytes_total = 262144 : index, comment = "Group DMA prefetch A chunk 3 (overlap compute g=2)"}> : () -> ()
    "elenor.runtime.group.dma_prefetch"() <{descriptor = "gdma_prefetch_B3", l2_slot = "l2_buf_B3", event = "ev_dma_B3", bytes_total = 65536 : index, comment = "Group DMA prefetch B chunk 3 (overlap compute g=2)"}> : () -> ()
    "elenor.runtime.group.wait_event"() <{event = "ev_dma_A0", comment = "Wait for A chunk 0 DMA"}> : () -> ()
    "elenor.runtime.group.wait_event"() <{event = "ev_dma_B0", comment = "Wait for B chunk 0 DMA"}> : () -> ()
    "elenor.runtime.group.dispatch_role"() <{role_id = 0 : index, event = "ev_role_c0", comment = "Dispatch tiles for group chunk 0"}> : () -> ()
    "elenor.runtime.group.wait_event"() <{event = "ev_dma_A1", comment = "Wait for A chunk 1 DMA"}> : () -> ()
    "elenor.runtime.group.wait_event"() <{event = "ev_dma_B1", comment = "Wait for B chunk 1 DMA"}> : () -> ()
    "elenor.runtime.group.dispatch_role"() <{role_id = 0 : index, event = "ev_role_c1", comment = "Dispatch tiles for group chunk 1"}> : () -> ()
    "elenor.runtime.group.wait_event"() <{event = "ev_dma_A2", comment = "Wait for A chunk 2 DMAd"}> : () -> ()
    "elenor.runtime.group.wait_event"() <{event = "ev_dma_B2", comment = "Wait for B chunk 2 DMA"}> : () -> ()
    "elenor.runtime.group.dispatch_role"() <{role_id = 0 : index, event = "ev_role_c2", comment = "Dispatch tiles for group chunk 2"}> : () -> ()
    "elenor.runtime.group.wait_event"() <{event = "ev_dma_A3", comment = "Wait for A chunk 3 DMA"}> : () -> ()
    "elenor.runtime.group.wait_event"() <{event = "ev_dma_B3", comment = "Wait for B chunk 3 DMA"}> : () -> ()
    "elenor.runtime.group.dispatch_role"() <{role_id = 0 : index, event = "ev_role_c3", comment = "Dispatch tiles for group chunk 3"}> : () -> ()
    "elenor.runtime.group.wait_event"() <{event = "ev_role_c0", comment = "Wait for chunk 0 tiles"}> : () -> ()
    "elenor.runtime.group.dma_store"() <{descriptor = "gdma_store_C0", l2_slot = "l2_buf_C0", event = "ev_dma_C0", bytes_total = 131072 : index, comment = "Group DMA store C chunk 0 L2->HBM"}> : () -> ()
    "elenor.runtime.group.wait_event"() <{event = "ev_role_c1", comment = "Wait for chunk 1 tiles"}> : () -> ()
    "elenor.runtime.group.dma_store"() <{descriptor = "gdma_store_C1", l2_slot = "l2_buf_C1", event = "ev_dma_C1", bytes_total = 131072 : index, comment = "Group DMA store C chunk 1 L2->HBM"}> : () -> ()
    "elenor.runtime.group.wait_event"() <{event = "ev_role_c2", comment = "Wait for chunk 2 tiles"}> : () -> ()
    "elenor.runtime.group.dma_store"() <{descriptor = "gdma_store_C2", l2_slot = "l2_buf_C2", event = "ev_dma_C2", bytes_total = 131072 : index, comment = "Group DMA store C chunk 2 L2->HBM"}> : () -> ()
    "elenor.runtime.group.wait_event"() <{event = "ev_role_c3", comment = "Wait for chunk 3 tiles"}> : () -> ()
    "elenor.runtime.group.dma_store"() <{descriptor = "gdma_store_C3", l2_slot = "l2_buf_C3", event = "ev_dma_C3", bytes_total = 131072 : index, comment = "Group DMA store C chunk 3 L2->HBM"}> : () -> ()
    "elenor.runtime.group.wait_event"() <{event = "ev_role_pow0", comment = "Pow tiles finished chunk 0"}> : () -> ()
    "elenor.runtime.group.dma_store"() <{descriptor = "gdma_store_pow0", l2_slot = "l2_buf_pow0", event = "ev_dma_pow_out0", bytes_total = 131072 : index, comment = "Pow output chunk 0 L2->HBM"}> : () -> ()
    "elenor.runtime.group.wait_event"() <{event = "ev_role_pow1", comment = "Pow tiles finished chunk 1"}> : () -> ()
    "elenor.runtime.group.dma_store"() <{descriptor = "gdma_store_pow1", l2_slot = "l2_buf_pow1", event = "ev_dma_pow_out1", bytes_total = 131072 : index, comment = "Pow output chunk 1 L2->HBM"}> : () -> ()
    "elenor.runtime.group.wait_event"() <{event = "ev_role_pow2", comment = "Pow tiles finished chunk 2"}> : () -> ()
    "elenor.runtime.group.dma_store"() <{descriptor = "gdma_store_pow2", l2_slot = "l2_buf_pow2", event = "ev_dma_pow_out2", bytes_total = 131072 : index, comment = "Pow output chunk 2 L2->HBM"}> : () -> ()
    "elenor.runtime.group.wait_event"() <{event = "ev_role_pow3", comment = "Pow tiles finished chunk 3"}> : () -> ()
    "elenor.runtime.group.dma_store"() <{descriptor = "gdma_store_pow3", l2_slot = "l2_buf_pow3", event = "ev_dma_pow_out3", bytes_total = 131072 : index, comment = "Pow output chunk 3 L2->HBM"}> : () -> ()
    "elenor.runtime.group.wait_event"() <{event = "ev_dma_C0", comment = "Drain store chunk 0 (overlap)"}> : () -> ()
    "elenor.runtime.group.wait_event"() <{event = "ev_dma_C1", comment = "Drain store chunk 1 (overlap)"}> : () -> ()
    "elenor.runtime.group.wait_event"() <{event = "ev_dma_C2", comment = "Drain store chunk 2 (overlap)"}> : () -> ()
    "elenor.runtime.group.wait_event"() <{event = "ev_dma_C3", comment = "Drain last store"}> : () -> ()
    "elenor.runtime.group.wait_event"() <{event = "ev_dma_pow_out0", comment = "Drain pow output chunk 0"}> : () -> ()
    "elenor.runtime.group.wait_event"() <{event = "ev_dma_pow_out1", comment = "Drain pow output chunk 1"}> : () -> ()
    "elenor.runtime.group.wait_event"() <{event = "ev_dma_pow_out2", comment = "Drain pow output chunk 2"}> : () -> ()
    "elenor.runtime.group.wait_event"() <{event = "ev_dma_pow_out3", comment = "Drain pow output chunk 3"}> : () -> ()
    "elenor.runtime.group.signal_event"() <{event = "group_task_done"}> : () -> ()
  }) : () -> ()
}) : () -> ()
