"""ELENOR runtime pipeline efficiency validator."""

from __future__ import annotations

from .cli import main
from .config import HardwareConfig, SimConfig, WorkloadConfig
from .dialects import Elenor
from .dialects.elenor import (
  AddOp,
  BOADescriptorOp,
  BranchEosOp,
  BranchOp,
  BranchPredicateOp,
  CollectiveRunOp,
  CompareOp,
  DispatchRoleOp,
  DMALoadOp,
  DMAStoreOp,
  EVUDescriptorOp,
  FenceOp,
  GroupBarrierOp,
  GroupDMAPrefetchOp,
  GroupDMAStoreOp,
  GroupWaitEventOp,
  InitStreamOp,
  LabelOp,
  LaunchBOAOp,
  LaunchEVUOp,
  LaunchMFEOp,
  LaunchUSEOp,
  LoadDescriptorOp,
  MFEDescriptorOp,
  MoveOp,
  NopOp,
  PatchDescriptorOp,
  ProfileBeginOp,
  ProfileEndOp,
  ReturnOp,
  SignalEventOp,
  StoreDescriptorOp,
  StreamAcquireOp,
  StreamDescOp,
  StreamEosOp,
  StreamPopOp,
  StreamPushOp,
  StreamReleaseOp,
  TileGroupTaskOp,
  TileProgramOp,
  TileRoleBindingOp,
  TrapOp,
  USEDescriptorOp,
  WaitAllOp,
  WaitOp,
)
from .engines import BOAEngine, EngineState, EVUEngine, MFEEngine, USEEngine
from .memory import L2SRAM, NoCRouter, PayloadTracker, SlotFrame
from .package import ElenorPackage
from .pmu import PMUCounter, StallReason
from .report import WorkloadReport  # noqa: F401
from .runtime import (
  DeviceRuntime,
  EventStatus,
  EventTable,
  FaultCode,
  FaultRecord,
  FaultRing,
  FirmwareRuntime,
  HostRuntime,
  KernelDriver,
  ProgramResidencyManager,
  ResetDomain,
)
from .simulator import Simulator
from .stream_queue import EOSPolicy, QueueKind, StreamQueue, StreamToken, TokenFlags
from .tile import ComputeTile, TileUCE
from .tile_group import TileGroup
from .tile_group_sequencer import TileGroupSequencer
from .trace import Tracer, trace_to_html
from .workload_builders import (
  make_attention_task,
  make_conv_relu_task,
  make_conv_relu_tile_program,
  make_identity_tile_program,
  make_matmul_task,
  make_matmul_tile_program,
  make_moe_task,
  make_paged_attention_task,
  make_paged_attention_tile_program,
  make_pow_task,
  make_pow_tile_program,
  make_stream_pipeline_tile_program,
  make_tiled_matmul_persistent_task,
  make_tiled_matmul_persistent_tile_program,
  make_tiled_matmul_pipelined_pow_task,
  make_tiled_matmul_pipelined_task,
  make_tiled_matmul_pow_nodep_task,
  make_tiled_matmul_task,
  make_tiled_matmul_tile_program,
  make_tiled_matmul_top_task,
)
from .workload_ir import (
  load_workload_ir,
  load_workload_ir_pretty,
  make_elenor_context,
  parse_workload_ir,
  parse_workload_ir_pretty,
  print_workload_ir,
  print_workload_ir_pretty,
  verify_workload_ir,
)
from .workloads import (
  AttentionWorkload,
  ConvReLuWorkload,
  MatmulWorkload,
  MoEWorkload,
  PagedAttentionWorkload,
  PowWorkload,
  TiledMatmulPipelinedPowWorkload,
  TiledMatmulPipelinedWorkload,
  TiledMatmulPowNodepWorkload,
  TiledMatmulTopWorkload,
  TiledMatmulWorkload,
  Workload,
)

__all__ = [
  "L2SRAM",
  "AddOp",
  "AttentionWorkload",
  "BOADescriptorOp",
  "BOAEngine",
  "BranchEosOp",
  "BranchOp",
  "BranchPredicateOp",
  "CollectiveRunOp",
  "CompareOp",
  "ComputeTile",
  "ConvReLuWorkload",
  "DMALoadOp",
  "DMAStoreOp",
  "DeviceRuntime",
  "DispatchRoleOp",
  "EOSPolicy",
  "EVUDescriptorOp",
  "EVUEngine",
  "Elenor",
  "ElenorPackage",
  "EngineState",
  "EventStatus",
  "EventTable",
  "FaultCode",
  "FaultRecord",
  "FaultRing",
  "FenceOp",
  "FirmwareRuntime",
  "GroupBarrierOp",
  "GroupDMAPrefetchOp",
  "GroupDMAStoreOp",
  "GroupWaitEventOp",
  "HardwareConfig",
  "HostRuntime",
  "InitStreamOp",
  "KernelDriver",
  "LabelOp",
  "LaunchBOAOp",
  "LaunchEVUOp",
  "LaunchMFEOp",
  "LaunchUSEOp",
  "LoadDescriptorOp",
  "MFEDescriptorOp",
  "MFEEngine",
  "MatmulWorkload",
  "MoEWorkload",
  "MoveOp",
  "NoCRouter",
  "NopOp",
  "PMUCounter",
  "PagedAttentionWorkload",
  "PatchDescriptorOp",
  "PayloadTracker",
  "PowWorkload",
  "ProfileBeginOp",
  "ProfileEndOp",
  "ProgramResidencyManager",
  "QueueKind",
  "ResetDomain",
  "ReturnOp",
  "SignalEventOp",
  "SimConfig",
  "Simulator",
  "SlotFrame",
  "StallReason",
  "StoreDescriptorOp",
  "StreamAcquireOp",
  "StreamDescOp",
  "StreamEosOp",
  "StreamPopOp",
  "StreamPushOp",
  "StreamQueue",
  "StreamReleaseOp",
  "StreamToken",
  "TileGroup",
  "TileGroupSequencer",
  "TileGroupTaskOp",
  "TileProgramOp",
  "TileRoleBindingOp",
  "TileUCE",
  "TiledMatmulPipelinedPowWorkload",
  "TiledMatmulPipelinedWorkload",
  "TiledMatmulPowNodepWorkload",
  "TiledMatmulTopWorkload",
  "TiledMatmulWorkload",
  "TokenFlags",
  "Tracer",
  "TrapOp",
  "USEDescriptorOp",
  "USEEngine",
  "WaitAllOp",
  "WaitOp",
  "Workload",
  "WorkloadConfig",
  "load_workload_ir",
  "load_workload_ir_pretty",
  "main",
  "make_attention_task",
  "make_conv_relu_task",
  "make_conv_relu_tile_program",
  "make_elenor_context",
  "make_identity_tile_program",
  "make_matmul_task",
  "make_matmul_tile_program",
  "make_moe_task",
  "make_paged_attention_task",
  "make_paged_attention_tile_program",
  "make_pow_task",
  "make_pow_tile_program",
  "make_stream_pipeline_tile_program",
  "make_tiled_matmul_persistent_task",
  "make_tiled_matmul_persistent_tile_program",
  "make_tiled_matmul_pipelined_pow_task",
  "make_tiled_matmul_pipelined_task",
  "make_tiled_matmul_pow_nodep_task",
  "make_tiled_matmul_task",
  "make_tiled_matmul_tile_program",
  "make_tiled_matmul_top_task",
  "parse_workload_ir",
  "parse_workload_ir_pretty",
  "print_workload_ir",
  "print_workload_ir_pretty",
  "trace_to_html",
  "verify_workload_ir",
]
